// Task state
#define TASK_STATE_READY 0
#define TASK_STATE_RUNNING 1
#define TASK_STATE_DONE 2
#define GPU_SEG_LOOP_START 0
#define GPU_SEG_LOOP_MID 1
#define GPU_SEG_LOOP_END 2
#define RUBIS_NO_INSTANCE 0