#include <ros/ros.h>
#include "autoware_msgs/ControlCommandStamped.h"
#include "geometry_msgs/TwistStamped.h"
#include "autoware_msgs/VehicleCmd.h"
#include <nav_msgs/Odometry.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <vector>