std_msgs/Header          header
int8                     GNSS_info_1
int8                     GNSS_info_2
int8                     Number_Sat
float32                  GNSS_Velocity_Latency
int8                     GNSS_Angles_Position_Type
float32                  GNSS_Heading
float32                  GNSS_Pitch
float32                  GNSS_GDOP
float32                  GNSS_PDOP
float32                  GNSS_HDOP
float32                  GNSS_VDOP
float32                  GNSS_TDOP
uint8                    New_GNSS_Flags
float64                  Diff_Age
geometry_msgs/Vector3    Pos_STD
float32                  Heading_STD
float32                  Pitch_STD
