// Generated by gencpp from file autoware_msgs/RecognizeLightStateResponse.msg
// DO NOT EDIT!


#ifndef AUTOWARE_MSGS_MESSAGE_RECOGNIZELIGHTSTATERESPONSE_H
#define AUTOWARE_MSGS_MESSAGE_RECOGNIZELIGHTSTATERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace autoware_msgs
{
template <class ContainerAllocator>
struct RecognizeLightStateResponse_
{
  typedef RecognizeLightStateResponse_<ContainerAllocator> Type;

  RecognizeLightStateResponse_()
    : class_id(0)
    , confidence(0.0)  {
    }
  RecognizeLightStateResponse_(const ContainerAllocator& _alloc)
    : class_id(0)
    , confidence(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _class_id_type;
  _class_id_type class_id;

   typedef float _confidence_type;
  _confidence_type confidence;





  typedef boost::shared_ptr< ::autoware_msgs::RecognizeLightStateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autoware_msgs::RecognizeLightStateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RecognizeLightStateResponse_

typedef ::autoware_msgs::RecognizeLightStateResponse_<std::allocator<void> > RecognizeLightStateResponse;

typedef boost::shared_ptr< ::autoware_msgs::RecognizeLightStateResponse > RecognizeLightStateResponsePtr;
typedef boost::shared_ptr< ::autoware_msgs::RecognizeLightStateResponse const> RecognizeLightStateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autoware_msgs::RecognizeLightStateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autoware_msgs::RecognizeLightStateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::autoware_msgs::RecognizeLightStateResponse_<ContainerAllocator1> & lhs, const ::autoware_msgs::RecognizeLightStateResponse_<ContainerAllocator2> & rhs)
{
  return lhs.class_id == rhs.class_id &&
    lhs.confidence == rhs.confidence;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::autoware_msgs::RecognizeLightStateResponse_<ContainerAllocator1> & lhs, const ::autoware_msgs::RecognizeLightStateResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace autoware_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::autoware_msgs::RecognizeLightStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autoware_msgs::RecognizeLightStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autoware_msgs::RecognizeLightStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autoware_msgs::RecognizeLightStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autoware_msgs::RecognizeLightStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autoware_msgs::RecognizeLightStateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autoware_msgs::RecognizeLightStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "62f293c02147ceff5911410a8e6c5070";
  }

  static const char* value(const ::autoware_msgs::RecognizeLightStateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x62f293c02147ceffULL;
  static const uint64_t static_value2 = 0x5911410a8e6c5070ULL;
};

template<class ContainerAllocator>
struct DataType< ::autoware_msgs::RecognizeLightStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autoware_msgs/RecognizeLightStateResponse";
  }

  static const char* value(const ::autoware_msgs::RecognizeLightStateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autoware_msgs::RecognizeLightStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 class_id\n"
"float32 confidence\n"
"\n"
;
  }

  static const char* value(const ::autoware_msgs::RecognizeLightStateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autoware_msgs::RecognizeLightStateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.class_id);
      stream.next(m.confidence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RecognizeLightStateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autoware_msgs::RecognizeLightStateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autoware_msgs::RecognizeLightStateResponse_<ContainerAllocator>& v)
  {
    s << indent << "class_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.class_id);
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOWARE_MSGS_MESSAGE_RECOGNIZELIGHTSTATERESPONSE_H
