(cl:defpackage autoware_msgs-srv
  (:use )
  (:export
   "RECOGNIZELIGHTSTATE"
   "<RECOGNIZELIGHTSTATE-REQUEST>"
   "RECOGNIZELIGHTSTATE-REQUEST"
   "<RECOGNIZELIGHTSTATE-RESPONSE>"
   "RECOGNIZELIGHTSTATE-RESPONSE"
  ))

