#ifndef INCLUDE_LANE_FOLLOWING_DEBUG_H_
#define INCLUDE_LANE_FOLLOWING_DEBUG_H_

#define DEBUG_ZONE_WARP 0
#define DEBUG_ZONE_COLOR_GRAD_THRESH 0
#define DEBUG_ZONE_FIND_LANES 0
#define DEBUG_ZONE_THREAD_WORKER 0
#define DEBUG_ZONE_THREAD_MANAGER 0
#define DEBUG_ZONE_THREAD_BASE 0
#define DEBUG_ZONE_LANE_BASE 0
#define DEBUG_ZONE_PROCESS 0
#define DEBUG_ZONE_ERROR 1
#define DEBUG_ZONE_FRAME 0
#define DEBUG_ZONE_ALL_PROC_STEPS 0
#define DEBUG_ZONE_TEST 0
#define DEBUG_ZONE_TEST_SPEED 0
#define DEBUG_ZONE_OUT_IMG 0
#define DEBUG_ZONE_ROS 1
#define DEBUG_ZONE_RAW_VIDEO 0

#define PRINT_DEBUG_MSG(x, ...) if ((x)) { printf(__VA_ARGS__); }

#endif /* INCLUDE_LANE_FOLLOWING_DEBUG_H_ */
