set(_CATKIN_CURRENT_PACKAGE "lidar_localizer")
set(lidar_localizer_VERSION "1.12.0")
set(lidar_localizer_MAINTAINER "kitsukawa <yuki@ertl.jp>")
set(lidar_localizer_PACKAGE_FORMAT "2")
set(lidar_localizer_BUILD_DEPENDS "autoware_config_msgs" "autoware_health_checker" "autoware_msgs" "eigen" "jsk_rviz_plugins" "libpcl-all-dev" "message_filters" "nav_msgs" "ndt_cpu" "ndt_gpu" "ndt_tku" "pcl_conversions" "pcl_omp_registration" "pcl_ros" "roscpp" "sensor_msgs" "std_msgs" "tf" "velodyne_pointcloud")
set(lidar_localizer_BUILD_EXPORT_DEPENDS "autoware_config_msgs" "autoware_health_checker" "autoware_msgs" "eigen" "jsk_rviz_plugins" "libpcl-all-dev" "message_filters" "nav_msgs" "ndt_cpu" "ndt_gpu" "ndt_tku" "pcl_conversions" "pcl_omp_registration" "pcl_ros" "roscpp" "sensor_msgs" "std_msgs" "tf" "velodyne_pointcloud")
set(lidar_localizer_BUILDTOOL_DEPENDS "autoware_build_flags" "catkin")
set(lidar_localizer_BUILDTOOL_EXPORT_DEPENDS )
set(lidar_localizer_EXEC_DEPENDS "autoware_config_msgs" "autoware_health_checker" "autoware_msgs" "eigen" "jsk_rviz_plugins" "libpcl-all-dev" "message_filters" "nav_msgs" "ndt_cpu" "ndt_gpu" "ndt_tku" "pcl_conversions" "pcl_omp_registration" "pcl_ros" "roscpp" "sensor_msgs" "std_msgs" "tf" "velodyne_pointcloud")
set(lidar_localizer_RUN_DEPENDS "autoware_config_msgs" "autoware_health_checker" "autoware_msgs" "eigen" "jsk_rviz_plugins" "libpcl-all-dev" "message_filters" "nav_msgs" "ndt_cpu" "ndt_gpu" "ndt_tku" "pcl_conversions" "pcl_omp_registration" "pcl_ros" "roscpp" "sensor_msgs" "std_msgs" "tf" "velodyne_pointcloud")
set(lidar_localizer_TEST_DEPENDS "rostest")
set(lidar_localizer_DOC_DEPENDS )
set(lidar_localizer_URL_WEBSITE "")
set(lidar_localizer_URL_BUGTRACKER "")
set(lidar_localizer_URL_REPOSITORY "")
set(lidar_localizer_DEPRECATED "")