# Unit of rate: hz
# Unit of task information: nano seconds

# 1s  : 1000000000
# 1ms : 1000000
# 1us : 1000
# 1ns : 1

#rate = hz
# other time unut = ns

# Sensing
ray_ground_filter:
  task_scheduling_flag: 0
  
  task_response_time_filename: "~/Documents/profiling/response_time/ray_ground_filter.csv"
  rate: 10 
  task_minimum_inter_release_time: 100000000
  task_execution_time: 100000000
  task_relative_deadline: 100000000
  
# Localization
voxel_grid_filter:
  task_scheduling_flag: 0
  
  task_response_time_filename: "~/Documents/profiling/response_time/voxel_grid_filter.csv"
  rate: 10 
  task_minimum_inter_release_time: 100000000
  task_execution_time: 100000000
  task_relative_deadline: 100000000

ndt_matching:
  localizer: "velodyne"

  task_scheduling_flag: 0
  
  task_response_time_filename: "~/Documents/profiling/response_time/ndt_matching.csv"
  rate: 100
  task_minimum_inter_release_time: 100000000
  task_execution_time: 70000000
  task_relative_deadline: 100000000

logger_brake_dist:
  rate: 10
  dist_filename: "~/Documents/profiling/response_time/dist.csv"

# Detection
calibration_publisher:
  calibration_file: "~/autoware.ai/autoware_files/data/calibration/single_lidar/Lexus2016RXHybrid.yaml"

lidar_euclidean_cluster_detect:
  task_scheduling_flag: 0
  
  task_response_time_filename: "~/Documents/profiling/response_time/lidar_euclidean_cluster_detect.csv"
  rate: 10
  task_minimum_inter_release_time: 100000000
  task_execution_time: 100000000
  task_relative_deadline: 100000000

vision_darknet_detect:
  task_scheduling_flag: 0
  
  task_response_time_filename: "~/Documents/profiling/response_time/vision_darknet_detect.csv"
  rate: 100
  task_minimum_inter_release_time: 100000000
  task_execution_time: 100000000
  task_relative_deadline: 100000000
  network_definition_file: "~/autoware.ai/autoware_files/vision/yolov3-320.cfg"
  pretrained_model_file: "~/autoware.ai/autoware_files/vision/yolov3.weights"

imm_ukf_pda_track:
  task_scheduling_flag: 0
  
  task_response_time_filename: "~/Documents/profiling/response_time/imm_ukf_pda_track.csv"
  rate: 10 
  task_minimum_inter_release_time: 100000000
  task_execution_time: 100000000
  task_relative_deadline: 100000000

range_vision_fusion:
  task_scheduling_flag: 0
  
  task_response_time_filename: "~/Documents/profiling/response_time/range_vision_fusion.csv"
  rate: 10 
  task_minimum_inter_release_time: 100000000
  task_execution_time: 100000000
  task_relative_deadline: 100000000

# Planning
op_global_planner:
  task_scheduling_flag: 0
  
  task_response_time_filename: "~/Documents/profiling/response_time/op_global_planner.csv"
  rate: 25 #25
  task_minimum_inter_release_time: 100000000
  task_execution_time: 100000000
  task_relative_deadline: 100000000
  multilap_flag: 0
  multilap_replanning_distance : 50

op_common_params:
  rollOutDensity: 4
  rollOutsNumber: 2
  maxVelocity: 10.0
  maxAcceleration: 10.0
  maxDeceleration: -10.0

op_trajectory_generator:
  task_scheduling_flag: 0
  
  task_response_time_filename: "~/Documents/profiling/response_time/op_trajectory_generator.csv"
  rate: 100 #100
  task_minimum_inter_release_time: 10000000
  task_execution_time: 10000000
  task_relative_deadline: 10000000

op_trajectory_evaluator:
  task_scheduling_flag: 0
  
  task_response_time_filename: "~/Documents/profiling/response_time/op_trajectory_evaluator.csv"
  rate: 100 #100
  task_minimum_inter_release_time: 100000000
  task_execution_time: 100000000
  task_relative_deadline: 100000000
  weightPriority: 0
  weightTransition: 5
  weightLong: 4
  weightLat: 4
  ImageWidth: 400
  ImageHeight: 400
  SprintDecisionTime: 9999999.0
  PedestrianStopImgHeightThreshold: 20
  PedestrianImageDetectionRange: 0.4
  # PedestrianRightThreshold: 1.0
  # PedestrianLeftThreshold: 1.0
  # VehicleImageDetectionRange: 1.0
  # VehicleImageWidthThreshold: 1.0


op_behavior_selector:
  task_scheduling_flag: 0
  
  task_response_time_filename: "~/Documents/profiling/response_time/op_behavior_selector.csv"
  rate: 100 #100
  task_minimum_inter_release_time: 10000000
  task_execution_time: 10000000
  task_relative_deadline: 10000000
  distanceToPedestrianThreshold: 15.0
  sprintSpeed: 10.0
  obstacleWaitingTimeinIntersection: 2.0
  turnThreshold: 30.0

op_motion_predictor:
  task_scheduling_flag: 0
  
  task_response_time_filename: "~/Documents/profiling/response_time/op_motion_predictor.csv"
  rate: 25 #25
  task_minimum_inter_release_time: 40000000
  task_execution_time: 40000000
  task_relative_deadline: 40000000

# Control
pure_pursuit:
  task_scheduling_flag: 0
  
  task_response_time_filename: "~/Documents/profiling/response_time/pure_pursuit.csv"
  rate: 30 #30
  task_minimum_inter_release_time: 33333333
  task_execution_time: 33333333
  task_relative_deadline: 33333333
  dynamic_params_flag: False
  dynamic_params_path: "~/autoware.ai/autoware_files/lgsvl_file/parameter/lgsvl_pure_pursuit.yaml"

twist_filter:
  task_scheduling_flag: 0
  
  task_response_time_filename: "~/Documents/profiling/response_time/twist_filter.csv"
  rate: 10
  task_minimum_inter_release_time: 100000000
  task_execution_time: 100000000
  task_relative_deadline: 100000000

twist_gate:
  task_scheduling_flag: 0
  
  task_response_time_filename: "~/Documents/profiling/response_time/twist_gate.csv"
  rate: 10
  task_minimum_inter_release_time: 100000000
  task_execution_time: 100000000
  task_relative_deadline: 100000000
  zero_flag: 0
