rosnode kill /lgsvl_triple_lidar_autorunner
# rosnode kill /websocket_bridge
# rosnode kill /lgsvl_traffic_signal_test
# rosnode kill /image_republisher
# rosnode kill /lidar_republisher_left
# rosnode kill /lidar_republisher_right
# rosnode kill /lidar_republisher_back
# rosnode kill /camera_republisher
# rosnode kill /gnss_republisher
# rosnode kill /base_link_to_gnss
# rosnode kill /base_link_to_velodyne
# rosnode kill /vector_map_loader
# rosnode kill /world_to_map
# rosnode kill /map_to_mobility
# rosnode kill /velodyne_to_velodyne_left
# rosnode kill /velodyne_to_velodyne_right
# rosnode kill /velodyne_to_velodyne_back
# rosnode kill /pcd_clipper_left
# rosnode kill /pcd_clipper_right
# rosnode kill /pcd_clipper_back
# rosnode kill /ray_ground_filter_left
# rosnode kill /ray_ground_filter_right
# rosnode kill /ray_ground_filter_back
# rosnode kill /voxel_grid_filter
# rosnode kill /gnss_localizer
# rosnode kill /pose_relay
# rosnode kill /vel_relay
# rosnode kill /vision_darknet_detect
# rosnode kill /yolo3_rects
# rosnode kill /calibration_publisher_left
# rosnode kill /calibration_publisher_right
# rosnode kill /lidar_euclidean_cluster_detect_left
# rosnode kill /lidar_euclidean_cluster_detect_right
# rosnode kill /lidar_euclidean_cluster_detect_back
# rosnode kill /imm_ukf_pda_left
# rosnode kill /imm_ukf_pda_right
# rosnode kill /imm_ukf_pda_back
# rosnode kill /range_vision_fusion_left
# rosnode kill /range_vision_fusion_right
# rosnode kill /detection/fusion_tools/range_fusion_visualization_left
# rosnode kill /detection/fusion_tools/range_fusion_visualization_right
# rosnode kill /detection/lidar_detector/cluster_detect_visualization_back
# rosnode kill /detection/lidar_detector/cluster_detect_visualization_left
# rosnode kill /detection/lidar_detector/cluster_detect_visualization_right
# rosnode kill /detection/object_tracker/ukf_track_visualization_back
# rosnode kill /detection/object_tracker/ukf_track_visualization_left
# rosnode kill /detection/object_tracker/ukf_track_visualization_right
# rosnode kill op_global_planner
# rosnode kill op_common_params
# rosnode kill op_trajectory_generator
# rosnode kill op_motion_predictor
# rosnode kill predicted_objects_visualizer
# rosnode kill op_trajectory_evaluator
# rosnode kill op_behavior_selector
# rosnode kill pure_pursuit
# rosnode kill twist_filter